image: python:3.7

stages:
  - test
  - build
  - deploy

test-python-36:
  stage: test
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run -m unittest -v
    - coverage report -m
  allow_failure: true

test-python-37:
  stage: test
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run -m unittest -v
    - coverage report -m
  allow_failure: true

test-python-38:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run -m unittest -v
    - coverage report -m
  allow_failure: true

pages:
  stage: build
  script:
  - pip install sphinx numpydoc
  - pip install -r requirements.txt
  - pip install .
  - cd docs && make html
  - mv build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

wheel-36:
  image: python:3.6
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

wheel-37:
  image: python:3.7
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

wheel-38:
  image: python:3.8
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist
      
# deploy:wheel:
#   stage: deploy
#   script:
#     - pip install twine
#     - twine upload dist/*
#   only:
#     #- master@daniel-williams/minke
#     - tags
#   # except:
#   #   - pushes
#   #   - web
