"""
End-to-end coverage for issue #153: "Support for multiple PSDs per event".

The underlying mechanism (`GravitationalWaveTransient._collect_psds`, in
``asimov/analysis.py``) already supports this in principle: a production can
either specify its own ``psds:`` block directly, or inherit PSDs from
whichever of its ``needs:`` dependencies produced them
(``pipeline.collect_assets()["psds"]``). This had never been exercised
end-to-end, so it was unclear whether it actually worked for the scenario
described in the issue -- generating PSDs via multiple methods, then
comparing PE outputs across them within a single project.

These tests drive the real ledger/apply_page/dependency-resolution code
paths (matching the style of ``tests/test_dependencies.py``), but substitute
lightweight fixture pipelines for BayesWave/Bilby so the tests run in
milliseconds instead of waiting on real analyses.
"""
import os
import shutil
import unittest
from unittest.mock import patch

import asimov.pipelines
from asimov.pipelines.testing.simple import SimpleTestPipeline
from asimov.cli.project import make_project
from asimov.cli.application import apply_page
from asimov.ledger import YAMLLedger

IFOS = ["H1", "L1"]


class _FakePSDPipeline(SimpleTestPipeline):
    """Stands in for a real PSD-estimation pipeline (e.g. BayesWave).

    Produces a ``psds`` asset keyed by interferometer, with a file unique to
    this production (its rundir is ``<working directory>/<production name>``),
    so that two different PSD-estimation productions for the same event never
    collide or get confused with one another.
    """

    name = "FakePSDPipeline"

    def collect_assets(self):
        assets = super().collect_assets()
        if not self.production.rundir:
            return assets
        os.makedirs(self.production.rundir, exist_ok=True)
        psds = {}
        for ifo in IFOS:
            psd_file = os.path.join(self.production.rundir, f"{ifo}-psd.dat")
            if not os.path.exists(psd_file):
                with open(psd_file, "w") as psd_fh:
                    psd_fh.write(
                        f"# Fake PSD for {ifo}, produced by {self.production.name}\n"
                    )
            psds[ifo] = psd_file
        assets["psds"] = psds
        return assets


class _FakePEPipeline(SimpleTestPipeline):
    """Stands in for a real PE pipeline (e.g. Bilby); produces no PSDs of its own."""

    name = "FakePEPipeline"


EVENT_BLUEPRINT = """
kind: event
name: GW150914_095045
interferometers:
- H1
- L1
"""


def _psd_blueprint(name):
    return f"""
kind: analysis
name: {name}
pipeline: fakepsdpipeline
comment: PSD estimation job
event: GW150914_095045
status: ready
"""


def _pe_blueprint(name, needs=None, psds=None):
    doc = f"""
kind: analysis
name: {name}
pipeline: fakepepipeline
comment: PE job
event: GW150914_095045
status: ready
"""
    if needs:
        doc += "needs:\n" + "\n".join(f"  - {n}" for n in needs) + "\n"
    if psds:
        doc += "psds:\n" + "\n".join(f"  {ifo}: {path}" for ifo, path in psds.items()) + "\n"
    return doc


class MultiplePSDsPerEventTests(unittest.TestCase):
    """Regression/coverage tests for issue #153."""

    @classmethod
    def setUpClass(cls):
        cls.cwd = os.getcwd()

    @classmethod
    def tearDownClass(cls):
        os.chdir(cls.cwd)

    def setUp(self):
        known_pipelines_patch = patch.dict(
            asimov.pipelines.known_pipelines,
            {
                "fakepsdpipeline": _FakePSDPipeline,
                "fakepepipeline": _FakePEPipeline,
            },
        )
        known_pipelines_patch.start()
        self.addCleanup(known_pipelines_patch.stop)

        os.makedirs(f"{self.cwd}/tests/tmp/multiple_psds_project")
        os.chdir(f"{self.cwd}/tests/tmp/multiple_psds_project")
        make_project(
            name="Test project", root=f"{self.cwd}/tests/tmp/multiple_psds_project"
        )
        self.ledger = YAMLLedger(".asimov/ledger.yml")

    def tearDown(self):
        del self.ledger
        os.chdir(self.cwd)
        shutil.rmtree(f"{self.cwd}/tests/tmp/multiple_psds_project")

    def _apply(self, contents, name):
        path = f"tests/tmp/multiple_psds_project/{name}.yaml"
        with open(f"{self.cwd}/{path}", "w") as blueprint_file:
            blueprint_file.write(contents)
        apply_page(file=f"{self.cwd}/{path}", ledger=self.ledger)

    def test_pe_productions_inherit_distinct_psds_from_their_own_dependency(self):
        """Two PE productions, each depending on a *different* PSD job for
        the same event, should each pick up only their own dependency's PSDs
        -- the scenario described in #153 (comparing bilby outputs across
        PSDs generated by different methods, within one project)."""
        self._apply(EVENT_BLUEPRINT, "event")
        self._apply(_psd_blueprint("BayesWavePSD"), "psd_bw")
        self._apply(_psd_blueprint("AltMethodPSD"), "psd_alt")
        self._apply(_pe_blueprint("Bilby_BW", needs=["BayesWavePSD"]), "pe_bw")
        self._apply(_pe_blueprint("Bilby_Alt", needs=["AltMethodPSD"]), "pe_alt")

        event = self.ledger.get_event("GW150914_095045")[0]
        productions = {p.name: p for p in event.productions}

        bw_psds = productions["BayesWavePSD"].pipeline.collect_assets()["psds"]
        alt_psds = productions["AltMethodPSD"].pipeline.collect_assets()["psds"]

        # Sanity check: the two PSD-generation methods actually produced
        # different PSDs (different files), otherwise this test would pass
        # trivially.
        self.assertNotEqual(bw_psds, alt_psds)

        self.assertEqual(productions["Bilby_BW"].psds, bw_psds)
        self.assertEqual(productions["Bilby_Alt"].psds, alt_psds)
        self.assertNotEqual(productions["Bilby_BW"].psds, productions["Bilby_Alt"].psds)

    def test_pe_production_with_explicit_psds_overrides_dependency(self):
        """A production can also specify `psds:` directly; this should be
        used as-is, regardless of any `needs:` dependency."""
        self._apply(EVENT_BLUEPRINT, "event")
        self._apply(_psd_blueprint("BayesWavePSD"), "psd_bw")
        explicit_psds = {"H1": "/tmp/explicit-H1.dat", "L1": "/tmp/explicit-L1.dat"}
        self._apply(
            _pe_blueprint("Bilby_Explicit", needs=["BayesWavePSD"], psds=explicit_psds),
            "pe_explicit",
        )

        event = self.ledger.get_event("GW150914_095045")[0]
        productions = {p.name: p for p in event.productions}

        self.assertEqual(productions["Bilby_Explicit"].psds, explicit_psds)

    def test_pe_production_with_no_psd_dependency_has_no_psds(self):
        """A PE production that doesn't depend on any PSD-producing job
        should simply have no PSDs, rather than picking one up by accident."""
        self._apply(EVENT_BLUEPRINT, "event")
        self._apply(_pe_blueprint("Bilby_NoPSD"), "pe_no_psd")

        event = self.ledger.get_event("GW150914_095045")[0]
        productions = {p.name: p for p in event.productions}

        self.assertEqual(productions["Bilby_NoPSD"].psds, {})
