name: 'Setup HTCondor'
description: 'Start and verify HTCondor service'
runs:
  using: "composite"
  steps:
    - name: Start HTCondor
      shell: bash
      run: |
        condor_master &
        for i in $(seq 1 30); do
          condor_status && break || sleep 3
        done
        condor_status
