name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  command:
    description: 'Full command to run inside the asimov env (include the asimov CLI if needed)'
    required: true
  working-directory:
    description: 'Working directory relative to GITHUB_WORKSPACE'
    default: 'test_project'
    required: false
  extra-env:
    description: 'Additional environment variables (e.g., "VAR1=value1 VAR2=value2")'
    default: ''
    required: false
  shell-setup:
    description: 'Additional shell setup commands to run before asimov command'
    default: ''
    required: false
  timeout:
    description: 'Command timeout in seconds (default 1800 = 30 min)'
    default: '1800'
    required: false
runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash
      run: |
        # Find conda executable - prefer CONDA_EXE, then default location
        echo "CONDA_EXE=${CONDA_EXE:-not set}"
        echo "Checking for conda..."
        
        if [ -n "${CONDA_EXE:-}" ] && [ -x "$CONDA_EXE" ]; then
          CONDA_BIN="$CONDA_EXE"
        elif [ -x "/usr/share/miniconda/bin/conda" ]; then
          CONDA_BIN="/usr/share/miniconda/bin/conda"
        elif [ -x "/opt/miniconda3/bin/conda" ]; then
          CONDA_BIN="/opt/miniconda3/bin/conda"
        elif [ -x "/root/miniconda3/bin/conda" ]; then
          CONDA_BIN="/root/miniconda3/bin/conda"
        elif command -v conda &> /dev/null; then
          CONDA_BIN=$(command -v conda)
        else
          echo "ERROR: Conda not found in any standard location" >&2
          echo "Searched: CONDA_EXE, /usr/share/miniconda, /opt/miniconda3, /root/miniconda3, PATH" >&2
          ls -la /usr/share/ 2>/dev/null | grep -i conda || true
          ls -la /opt/ 2>/dev/null | grep -i conda || true
          exit 1
        fi
        
        # Prefer the real bin/conda instead of condabin shim
        if [[ "$CONDA_BIN" == */condabin/conda ]]; then
          CONDA_BIN="${CONDA_BIN%/condabin/conda}/bin/conda"
        fi
        if command -v realpath >/dev/null 2>&1; then
          CONDA_BIN=$(realpath "$CONDA_BIN" 2>/dev/null || echo "$CONDA_BIN")
        fi
        echo "Using conda at: $CONDA_BIN"
        
        # Build the command to run; workspace is pre-owned by submituser in the workflow step
        WORKDIR_IN="${{ inputs.working-directory }}"
        EXTRA_ENV='${{ inputs.extra-env }}'
        SHELL_SETUP='${{ inputs.shell-setup }}'
        COMMAND_RAW='${{ inputs.command }}'
        TIMEOUT_SECS='${{ inputs.timeout }}'

        if [[ "$WORKDIR_IN" = /* ]]; then
          WORKDIR="$WORKDIR_IN"
        else
          WORKDIR="$GITHUB_WORKSPACE/$WORKDIR_IN"
        fi

        # Ensure the working directory exists
        mkdir -p "$WORKDIR"

        # Run as submituser with login shell and explicit conda init
        su submituser -l -s /bin/bash -c '
          set -eo pipefail
          CONDA_BIN="$1"
          WORKDIR="$2"
          EXTRA_ENV="$3"
          SHELL_SETUP="$4"
          CMD_RAW="$5"
          TIMEOUT_SECS="$6"
          
          # Explicitly source conda initialization
          source "$(dirname "$CONDA_BIN")/../etc/profile.d/conda.sh" 2>/dev/null || true
          
          if [ -n "$EXTRA_ENV" ]; then eval "$EXTRA_ENV"; fi
          if [ -n "$SHELL_SETUP" ]; then eval "$SHELL_SETUP"; fi
          cd "$WORKDIR"
          
          # Run with timeout; activate env explicitly to ensure PATH is set
          timeout "$TIMEOUT_SECS" conda activate asimov && bash -c "$CMD_RAW"
        ' -- "$CONDA_BIN" "$WORKDIR" "$EXTRA_ENV" "$SHELL_SETUP" "$COMMAND_RAW" "$TIMEOUT_SECS"
