name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  script:
    description: 'Full script to run inside the asimov env (include the asimov CLI if needed)'
    required: true


runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash -el {0}
      run: |
        CONDA_EXE="${CONDA_EXE:-$(which conda)}"
        su - submituser <<SUBMITUSER
        set -euo pipefail
        cd "$GITHUB_WORKSPACE"
        $CONDA_EXE run -n asimov --no-capture-output ${{ inputs.script }}
        SUBMITUSER