name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  script:
    description: 'Full sript to run inside the asimov env (include the asimov CLI if needed)'
    required: true


runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash -el {0}
      run: |
        echo $CONDA 
        echo $CONDA_EXE 

        CONDA_EXE=/__w/asimov/asimov/3/condabin/conda
        ASIMOV_CMD="$CONDA_EXE run -n asimov"

        su - submituser <<EOF
        set -euo pipefail
        cd "$GITHUB_WORKSPACE"
        COMMAND_SAFE=$(printf '%q' '${{ inputs.script }}')
        "$ASIMOV_CMD" bash -c $COMMAND_SAFE
        EOF