name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  command:
    description: 'Full command to run inside the asimov env (include the asimov CLI if needed)'
    required: true
  working-directory:
    description: 'Working directory relative to GITHUB_WORKSPACE'
    default: 'test_project'
    required: false
  extra-env:
    description: 'Additional environment variables (e.g., "VAR1=value1 VAR2=value2")'
    default: ''
    required: false
  shell-setup:
    description: 'Additional shell setup commands to run before asimov command'
    default: ''
    required: false
  timeout:
    description: 'Command timeout in seconds (default 1800 = 30 min)'
    default: '1800'
    required: false
runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash
      run: |
        # Build the command variables
        WORKDIR_IN="${{ inputs.working-directory }}"
        EXTRA_ENV='${{ inputs.extra-env }}'
        SHELL_SETUP='${{ inputs.shell-setup }}'
        COMMAND_RAW='${{ inputs.command }}'
        TIMEOUT_SECS='${{ inputs.timeout }}'

        if [[ "$WORKDIR_IN" = /* ]]; then
          WORKDIR="$WORKDIR_IN"
        else
          WORKDIR="$GITHUB_WORKSPACE/$WORKDIR_IN"
        fi

        # Ensure the working directory exists
        mkdir -p "$WORKDIR"

        # Run as submituser with explicit conda initialization
        su submituser -l -s /bin/bash -c '
          set -eo pipefail
          WORKDIR="$1"
          EXTRA_ENV="$2"
          SHELL_SETUP="$3"
          CMD_RAW="$4"
          TIMEOUT_SECS="$5"
          
          # Explicitly initialize conda for submituser (they are a fresh user)
          __conda_setup="$(/usr/share/miniconda/bin/conda shell.bash hook 2> /dev/null)"
          if [ $? -eq 0 ]; then
              eval "$__conda_setup"
          else
              if [ -f "/usr/share/miniconda/etc/profile.d/conda.sh" ]; then
                  . "/usr/share/miniconda/etc/profile.d/conda.sh"
              else
                  export PATH="/usr/share/miniconda/bin:$PATH"
              fi
          fi
          unset __conda_setup
          
          if [ -n "$EXTRA_ENV" ]; then eval "$EXTRA_ENV"; fi
          if [ -n "$SHELL_SETUP" ]; then eval "$SHELL_SETUP"; fi
          cd "$WORKDIR"
          
          # Run command in asimov environment
          timeout "$TIMEOUT_SECS" conda run -n asimov bash -c "$CMD_RAW"
        ' -- "$WORKDIR" "$EXTRA_ENV" "$SHELL_SETUP" "$COMMAND_RAW" "$TIMEOUT_SECS"
