name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  command:
    description: 'Arguments to the Asimov CLI (do NOT include the leading "asimov"; it is added automatically)'
    required: true
  working-directory:
    description: 'Working directory relative to GITHUB_WORKSPACE'
    default: 'test_project'
    required: false
  extra-env:
    description: 'Additional environment variables (e.g., "VAR1=value1 VAR2=value2")'
    default: ''
    required: false
  shell-setup:
    description: 'Additional shell setup commands to run before asimov command'
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash
      run: |
        # Find conda executable - prefer CONDA_EXE, then default location
        echo "CONDA_EXE=${CONDA_EXE:-not set}"
        echo "Checking for conda..."
        
        if [ -n "${CONDA_EXE:-}" ] && [ -x "$CONDA_EXE" ]; then
          CONDA_BIN="$CONDA_EXE"
        elif [ -x "/usr/share/miniconda/bin/conda" ]; then
          CONDA_BIN="/usr/share/miniconda/bin/conda"
        elif [ -x "/opt/miniconda3/bin/conda" ]; then
          CONDA_BIN="/opt/miniconda3/bin/conda"
        elif [ -x "/root/miniconda3/bin/conda" ]; then
          CONDA_BIN="/root/miniconda3/bin/conda"
        elif command -v conda &> /dev/null; then
          CONDA_BIN=$(command -v conda)
        else
          echo "ERROR: Conda not found in any standard location" >&2
          echo "Searched: CONDA_EXE, /usr/share/miniconda, /opt/miniconda3, /root/miniconda3, PATH" >&2
          ls -la /usr/share/ 2>/dev/null | grep -i conda || true
          ls -la /opt/ 2>/dev/null | grep -i conda || true
          exit 1
        fi
        
        echo "Using conda at: $CONDA_BIN"
        
        # Build the command to run
        WORKDIR="${{ inputs.working-directory }}"
        
        # Run as submituser WITHOUT login shell (no -) so env vars are preserved
        # Pass variables explicitly in the command
        su submituser bash <<'SCRIPT_END'
        export CONDA_BIN='$CONDA_BIN'
        export GITHUB_WORKSPACE='$GITHUB_WORKSPACE'
        cd "$GITHUB_WORKSPACE/$WORKDIR"
        
        # Set additional environment variables if provided
        EXTRA_ENV='${{ inputs.extra-env }}'
        if [ -n "$EXTRA_ENV" ]; then
          # Process each KEY=VALUE pair (space or newline separated)
          # Note: values cannot contain spaces when using space-separated format
          while IFS= read -r line; do
            [ -z "$line" ] && continue
            # Validate format: KEY=VALUE
            if [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*=.*$ ]]; then
              export "$line"
            else
              echo "Warning: Skipping invalid environment variable format: $line" >&2
            fi
          done < <(echo "$EXTRA_ENV" | tr ' ' '\n')
        fi
        
        # Run shell setup commands if provided
        SHELL_SETUP='${{ inputs.shell-setup }}'
        if [ -n "$SHELL_SETUP" ]; then
          eval "$SHELL_SETUP"
        fi
        
        # Execute the asimov command(s)
        # The command input is trusted as it comes from the workflow file (repository code)
        # and may contain multi-line commands and shell features (pipes, redirects, etc.)
        COMMAND='${{ inputs.command }}'
        
        # Handle multiline commands by prefixing each non-empty line with "asimov"
        line_count=$(echo "$COMMAND" | wc -l)
        if [ "$line_count" -gt 1 ]; then
          # Multiline: prefix each non-empty line with "asimov"
          PREFIXED_COMMAND=$(echo "$COMMAND" | sed '/^[[:space:]]*$/d' | sed 's/^/asimov /')
          $CONDA_BIN run -n asimov bash -c "$PREFIXED_COMMAND"
        else
          # Single line: just prefix with "asimov"
          $CONDA_BIN run -n asimov bash -c "asimov $COMMAND"
        fi
        SCRIPT_END
