name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  command:
    description: 'Asimov command to run (without asimov prefix)'
    required: true
  working-directory:
    description: 'Working directory relative to GITHUB_WORKSPACE'
    default: 'test_project'
    required: false
  extra-env:
    description: 'Additional environment variables (e.g., "VAR1=value1 VAR2=value2")'
    default: ''
    required: false
  shell-setup:
    description: 'Additional shell setup commands to run before asimov command'
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash
      run: |
        # Find conda executable - look in common locations
        if [ -n "${CONDA_EXE:-}" ] && [ -x "$CONDA_EXE" ]; then
          CONDA_BIN="$CONDA_EXE"
        elif [ -n "${CONDA:-}" ] && [ -x "${CONDA}/bin/conda" ]; then
          CONDA_BIN="${CONDA}/bin/conda"
        elif [ -x "/usr/share/miniconda/bin/conda" ]; then
          CONDA_BIN="/usr/share/miniconda/bin/conda"
        elif [ -x "/opt/miniconda3/bin/conda" ]; then
          CONDA_BIN="/opt/miniconda3/bin/conda"
        else
          # Try to find conda in PATH
          CONDA_BIN=$(which conda)
        fi
        
        if [ ! -x "$CONDA_BIN" ]; then
          echo "Conda not found" >&2
          exit 1
        fi
        
        # Create a temporary script to run as submituser
        SCRIPT_FILE=$(mktemp)
        trap "rm -f $SCRIPT_FILE" EXIT
        
        cat > "$SCRIPT_FILE" <<'SCRIPT_EOF'
        set -euo pipefail
        cd "$1"
        $2
        $3
        $4 run -n asimov asimov $5
        SCRIPT_EOF
        
        chmod +x "$SCRIPT_FILE"
        
        # Run the script as submituser with all parameters
        su - submituser "$SCRIPT_FILE" \
          "$GITHUB_WORKSPACE/${{ inputs.working-directory }}" \
          "${{ inputs.extra-env }}" \
          "${{ inputs.shell-setup }}" \
          "$CONDA_BIN" \
          "${{ inputs.command }}"
