name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  command:
    description: 'Asimov command to run (without asimov prefix)'
    required: true
  working-directory:
    description: 'Working directory relative to GITHUB_WORKSPACE'
    default: 'test_project'
    required: false
  extra-env:
    description: 'Additional environment variables (e.g., "VAR1=value1 VAR2=value2")'
    default: ''
    required: false
  shell-setup:
    description: 'Additional shell setup commands to run before asimov command'
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash
      run: |
        # Find conda executable - look in common locations
        if [ -n "${CONDA_EXE:-}" ] && [ -x "$CONDA_EXE" ]; then
          CONDA_BIN="$CONDA_EXE"
        elif [ -n "${CONDA:-}" ] && [ -x "${CONDA}/bin/conda" ]; then
          CONDA_BIN="${CONDA}/bin/conda"
        elif [ -x "/usr/share/miniconda/bin/conda" ]; then
          CONDA_BIN="/usr/share/miniconda/bin/conda"
        elif [ -x "/opt/miniconda3/bin/conda" ]; then
          CONDA_BIN="/opt/miniconda3/bin/conda"
        else
          # Try to find conda in PATH
          CONDA_BIN=$(which conda)
        fi
        
        if [ ! -x "$CONDA_BIN" ]; then
          echo "Conda not found" >&2
          exit 1
        fi
        
        # Store variables for use in heredoc
        WORKDIR="$GITHUB_WORKSPACE/${{ inputs.working-directory }}"
        EXTRA_ENV="${{ inputs.extra-env }}"
        COMMAND="${{ inputs.command }}"
        
        su - submituser <<'EOSU'
        set -euo pipefail
        cd "'"$WORKDIR"'"
        $EXTRA_ENV
        ${{ inputs.shell-setup }}
        $CONDA_BIN run -n asimov asimov $COMMAND
        EOSU
