name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  script:
    description: 'Full script to run inside the asimov env (include the asimov CLI if needed)'
    required: true


runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash -el {0}
      run: |
        su -m - submituser <<SUBMITUSER
        echo "Setting environment"
        set -euo pipefail
        echo "Switching to the github workspace"
        cd "$GITHUB_WORKSPACE"
        echo "Running command in asimov conda environment"
        echo $CONDA_ENV
        echo "Quoting the command to be safe"
        COMMAND_SAFE=$(printf '%q' '${{ inputs.script }}' | xargs)
        echo $COMMAND_SAFE
        echo "Running the quoted command"
        $CONDA_EXE run -n asimov bash -s <<'SCRIPT'
        ${{ inputs.script }}
        SCRIPT
        SUBMITUSER