name: 'Run Asimov Command'
description: 'Execute asimov command as submituser'
inputs:
  script:
    description: 'Full sript to run inside the asimov env (include the asimov CLI if needed)'
    required: true


runs:
  using: "composite"
  steps:
    - name: Run asimov command
      shell: bash -el {0}
      run: |
        su - submituser <<EOF
        set -euo pipefail
        cd "$GITHUB_WORKSPACE"
        echo $CONDA_ENV
        COMMAND_SAFE=$(printf '%q' '${{ inputs.script }}')
        $CONDA_EXE run -n asimov bash -c $COMMAND_SAFE
        EOF